=== BMT-StealthGroup/credential-commons/dist/schemas/public/Credential/GenericId.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "civ:Credential:GenericId",
  "type": "object",
  "properties": {
    "id": {
      "type": [
        "null",
        "string"
      ]
    },
    "issuer": {
      "type": "string"
    },
    "issued": {
      "type": "string"
    },
    "identifier": {
      "type": "string"
    },
    "expiry": {
      "type": [
        "null",
        "string"
      ]
    },
    "version": {
      "type": "number"
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "claims": {
      "type": "object",
      "properties": {
        "type": {
          "type": "object",
          "properties": {
            "address": {
              "type": "object",
              "properties": {
                "city": {
                  "type": "string"
                },
                "country": {
                  "type": "string"
                },
                "county": {
                  "type": "string"
                },
                "state": {
                  "type": "string"
                },
                "street": {
                  "type": "string"
                },
                "unit": {
                  "type": "string"
                },
                "zipCode": {
                  "type": "string"
                }
              }
            },
            "documentType": {
              "type": "string"
            },
            "image": {
              "type": "object",
              "properties": {
                "image": {
                  "type": "string"
                },
                "md5": {
                  "type": "string"
                }
              }
            }
          }
        },
        "identity": {
          "type": "object",
          "properties": {
            "dateOfBirth": {
              "type": "object",
              "properties": {
                "day": {
                  "type": "number"
                },
                "month": {
                  "type": "number"
                },
                "year": {
                  "type": "number"
                }
              }
            },
            "name": {
              "type": "object",
              "properties": {
                "first": {
                  "type": "string"
                },
                "last": {
                  "type": "string"
                },
                "middle": {
                  "type": "string"
                },
                "nickname": {
                  "type": "string"
                }
              }
            },
            "givenName": {
              "type": "string"
            },
            "dateOfIssue": {
              "type": "object",
              "properties": {
                "day": {
                  "type": "number"
                },
                "month": {
                  "type": "number"
                },
                "year": {
                  "type": "number"
                }
              }
            },
            "dateOfExpiry": {
              "type": "object",
              "properties": {
                "day": {
                  "type": "number"
                },
                "month": {
                  "type": "number"
                },
                "year": {
                  "type": "number"
                }
              }
            }
          }
        }
      }
    },
    "signature": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "merkleRoot": {
          "type": "string"
        },
        "anchor": {
          "type": "object",
          "properties": {
            "subject": {
              "type": "object",
              "properties": {
                "pub": {
                  "type": "string"
                },
                "label": {
                  "type": "string"
                },
                "data": {
                  "type": "string"
                },
                "signature": {
                  "type": "string"
                }
              }
            },
            "walletId": {
              "type": "string"
            },
            "cosigners": {
              "type": "array",
              "items": {
                "type": "object"
              }
            },
            "authority": {
              "type": "object",
              "properties": {
                "pub": {
                  "type": "string"
                },
                "path": {
                  "type": "string"
                }
              }
            },
            "coin": {
              "type": "string"
            },
            "tx": {
              "type": "string"
            },
            "network": {
              "type": "string"
            },
            "value": {
              "type": "number"
            },
            "type": {
              "type": "string"
            },
            "civicAsPrimary": {
              "type": "boolean"
            },
            "schema": {
              "type": "string"
            }
          }
        },
        "leaves": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    }
  },
  "additionalProperties": false
}

=== BMT-StealthGroup/credential-commons/__test__/creds/fixtures/VCPermanentAnchor.json
{
  "id": null,
  "issuer": "jest:test",
  "issued": "2018-07-02T23:49:31.182Z",
  "identifier": "civ:Credential:SimpleTest",
  "expiry": null,
  "version": 1,
  "type": [
    "Credential",
    "civ:Credential:SimpleTest"
  ],
  "claims": {
    "identity": {
      "name": {
        "first": "Joao",
        "last": "Santos",
        "middle": "Barbosa"
      },
      "dateOfBirth": {
        "day": 20,
        "month": 3,
        "year": 1978
      }
    }
  },
  "signature": {
    "type": "CivicMerkleProof2018",
    "merkleRoot": "8255e2a67230a6d3b6965b6807ee46c2dca4429f5fa3d4ecad20f5619e440869",
    "anchor": {
      "schema": "tbch-20180201",
      "walletId": "5b3aba58fe59b14f05e5ff3453d525d3",
      "civicAsPrimary": true,
      "tx": "02000000015d1b93cbf8a5b7aaccbfcda011ba6d321a31818e386e00309680d01fff7c8b1600000000fdfd0000473044022078fd745181765ab6d579ac1cea964f19d795f8361020e882730cfbe4ee71c797022008f790ed892ec38acadfe64e2b85fde44244b1822679189b00a2210013ff364f41483045022100f3c2f915682b1aecf82b04b5b57236dcf613927f3aae421dea659979081be4e2022052c9c302b46cd000ed74375a9e4ab73a5ba00bb73bb8a4a6934f15d2630c2b07414c69522102153b09ec29834902b2557f953439c0f5133344b3012a369d5c8be9f8d6a1185921025c720eebc2cfa8d29cc375437ebfadb479ac3766f0f0d40182e9aa027d7cfc9b2103637ff6b19011da10ab49f786cd401e595648d71d3cbcd3ae2f7eccd74b97627b53aeffffffff02caef50020000000017a91462ce37e7c32f86ae67294f01501ead9d8c4f3c8787fb1700000000000017a914901c0b0bc80750f59fd78d5d59546743f88d81048700000000",
      "subject": {
        "label": "civ:Credential:SimpleTest",
        "pub": "xpub661MyMwAqRbcFNXRK7kdsoidhiyfqiwhVhbphdKZjqnik83L1w1mWsPwVrsvbRrPa7sysiJRRBxr6jyrCbPScdXkhSjyYtQtFfwxGBwrBzn",
        "data": "8255e2a67230a6d3b6965b6807ee46c2dca4429f5fa3d4ecad20f5619e440869",
        "signature": "3044022051612859c8da75d54f34245a1404cf84920dd5268b923ad8bf67b0d8729a52db02207c76cc309b240ab4585b6f25a5752d7ac72438e9e3ab0113150770cf23bb90b6"
      },
      "authority": {
        "pub": "xpub661MyMwAqRbcGYsJt9oHuATcFJT277ajoJdwFsM23mxumR6xU4dvDRyNFE35Mshe1poDBwsiKAAuG2ayGq7rwUuzz1JS5at56MAzfVyBtud",
        "path": "/0/0/1/920"
      },
      "cosigners": [
        {
          "pub": "xpub661MyMwAqRbcGYsJt9oHuATcFJT277ajoJdwFsM23mxumR6xU4dvDRyNFE35Mshe1poDBwsiKAAuG2ayGq7rwUuzz1JS5at56MAzfVyBtud"
        },
        {
          "pub": "xpub661MyMwAqRbcFekghv3i7EtjPmuEHvcVHxDatibF3JhhdaynmDvQex1aB4JhzgJq4e1EgVeuGDtqoaAdnBuyk2uWFwDz1CdfaVgREdUp23Q"
        }
      ],
      "type": "permanent",
      "value": 38865585,
      "coin": "tbch",
      "network": "testnet"
    },
    "leaves": [{
      "identifier": "civ:Identity:name",
      "value": "urn:first:36c71aa342178c88f692fe6df827c71cc08f1ae65874024a2eb3805a969528e0:Joao|urn:last:144a8d05ea7c58e82f96845637a0a07b2efe601624daeaa95071d06dc2437b69:Santos|urn:middle:b5f12ff1f98793f61b89cfb02837ce08276f465a87f6b86b96996c93aeb69e6d:Barbosa|",
      "claimPath": "identity.name",
      "targetHash": "c5c542c47671322d8e6c80d380fe8dd01cd6cbf2a3134ba7cf5db53c9dbc1fa0",
      "proof": [{
        "right": "a48407c904094e3ca52a43f66553f74730fc6fc27e00966154c97907ad312da2"
      },
        {
          "right": "9d8ac4b4f10bd39731b551dfabe142991de1f8c915d32dd8353abcfdd66ff746"
        },
        {
          "right": "78823dfa5067cbcb7f578f0afbabbb9389993da0f11436a8b08c5d671447a686"
        },
        {
          "right": "639fee662f799852b5e35537d033c80e46bdcf5224d9593009b5e68cbe166f76"
        },
        {
          "right": "7931d7f2b94b0845b776ec6d92da7b76b7a6f23859d80a15f8650c46f8d6b415"
        }
      ]
    },
      {
        "identifier": "civ:Identity:name.first",
        "value": "urn:first:36c71aa342178c88f692fe6df827c71cc08f1ae65874024a2eb3805a969528e0:Joao",
        "claimPath": "identity.name.first",
        "targetHash": "a48407c904094e3ca52a43f66553f74730fc6fc27e00966154c97907ad312da2",
        "proof": [{
          "left": "c5c542c47671322d8e6c80d380fe8dd01cd6cbf2a3134ba7cf5db53c9dbc1fa0"
        },
          {
            "right": "9d8ac4b4f10bd39731b551dfabe142991de1f8c915d32dd8353abcfdd66ff746"
          },
          {
            "right": "78823dfa5067cbcb7f578f0afbabbb9389993da0f11436a8b08c5d671447a686"
          },
          {
            "right": "639fee662f799852b5e35537d033c80e46bdcf5224d9593009b5e68cbe166f76"
          },
          {
            "right": "7931d7f2b94b0845b776ec6d92da7b76b7a6f23859d80a15f8650c46f8d6b415"
          }
        ]
      },
      {
        "identifier": "civ:Identity:name.middle",
        "value": "urn:middle:b5f12ff1f98793f61b89cfb02837ce08276f465a87f6b86b96996c93aeb69e6d:Barbosa",
        "claimPath": "identity.name.middle",
        "targetHash": "d8fe45352b1217b06ab004d62052fcf77929ca40cc36ba8896f6df5614b764f7",
        "proof": [{
          "right": "bf89d2ca3fd74b96859e6af82973ef5fad676ad8fd6035d049bd5888b9c39ec3"
        },
          {
            "left": "bd2c1c5560ef461fad14bbc455939b0c756bee63228df6c2391ea4307b7493ca"
          },
          {
            "right": "78823dfa5067cbcb7f578f0afbabbb9389993da0f11436a8b08c5d671447a686"
          },
          {
            "right": "639fee662f799852b5e35537d033c80e46bdcf5224d9593009b5e68cbe166f76"
          },
          {
            "right": "7931d7f2b94b0845b776ec6d92da7b76b7a6f23859d80a15f8650c46f8d6b415"
          }
        ]
      },
      {
        "identifier": "civ:Identity:name.last",
        "value": "urn:last:144a8d05ea7c58e82f96845637a0a07b2efe601624daeaa95071d06dc2437b69:Santos",
        "claimPath": "identity.name.last",
        "targetHash": "bf89d2ca3fd74b96859e6af82973ef5fad676ad8fd6035d049bd5888b9c39ec3",
        "proof": [{
          "left": "d8fe45352b1217b06ab004d62052fcf77929ca40cc36ba8896f6df5614b764f7"
        },
          {
            "left": "bd2c1c5560ef461fad14bbc455939b0c756bee63228df6c2391ea4307b7493ca"
          },
          {
            "right": "78823dfa5067cbcb7f578f0afbabbb9389993da0f11436a8b08c5d671447a686"
          },
          {
            "right": "639fee662f799852b5e35537d033c80e46bdcf5224d9593009b5e68cbe166f76"
          },
          {
            "right": "7931d7f2b94b0845b776ec6d92da7b76b7a6f23859d80a15f8650c46f8d6b415"
          }
        ]
      },
      {
        "identifier": "civ:Identity:dateOfBirth",
        "value": "urn:day:21b431a5d5430b312f065ea634bd32616a19d017fa8bedea7b89b77d47d27fdf:00000020|urn:month:cd4a66b450deef9c1022b0882e0891de4e721018dc039538f9d466699696a583:00000003|urn:year:493e2d3a8044d30430de6eb961fb9105ccf4f0f30297f1ef54e6a1a9bd3aee0f:00001978|",
        "claimPath": "identity.dateOfBirth",
        "targetHash": "1488396304d6cb3ed6b0f091c66b5d540a9ddf1507e910af528a9a38079e3e6e",
        "proof": [{
          "right": "7dea72a2b2f39f2b792cd950cab6de2f5c7870560419d7231166979bb2a78342"
        },
          {
            "right": "682cba2278591a4c8306d5b92dc6a51c596b2f6b7a09c4700b4196b3e4dc6174"
          },
          {
            "left": "2da9b9faee33ebb6abfecef71576f706ef5a616508a49163b772d52131580879"
          },
          {
            "right": "639fee662f799852b5e35537d033c80e46bdcf5224d9593009b5e68cbe166f76"
          },
          {
            "right": "7931d7f2b94b0845b776ec6d92da7b76b7a6f23859d80a15f8650c46f8d6b415"
          }
        ]
      },
      {
        "identifier": "civ:Meta:issuer",
        "value": "urn:issuer:aaec07b09ee3406d59fbd065202e6172c316b529db5e15a5701ee38580c0e168:jest:test",
        "claimPath": "meta.issuer",
        "targetHash": "7dea72a2b2f39f2b792cd950cab6de2f5c7870560419d7231166979bb2a78342",
        "proof": [{
          "left": "1488396304d6cb3ed6b0f091c66b5d540a9ddf1507e910af528a9a38079e3e6e"
        },
          {
            "right": "682cba2278591a4c8306d5b92dc6a51c596b2f6b7a09c4700b4196b3e4dc6174"
          },
          {
            "left": "2da9b9faee33ebb6abfecef71576f706ef5a616508a49163b772d52131580879"
          },
          {
            "right": "639fee662f799852b5e35537d033c80e46bdcf5224d9593009b5e68cbe166f76"
          },
          {
            "right": "7931d7f2b94b0845b776ec6d92da7b76b7a6f23859d80a15f8650c46f8d6b415"
          }
        ]
      },
      {
        "identifier": "civ:Meta:issued",
        "value": "urn:issued:82ad8350c9352b6d1e3556e0a3190c1ab3ec77c13b98d979f3bae3199410b2ac:2018-07-02T23:49:31.182Z",
        "claimPath": "meta.issued",
        "targetHash": "cd513b3ce7d8a6c6a97d498cd6cce442fb6f7ee137422dc10821bf965e0bf0b2",
        "proof": [{
          "right": "f4c91aa2bc7cbc6bfeb53b400e70da46decda2386d58d01247576aee4d711157"
        },
          {
            "left": "4c236169fd5e02d5154457f3fc8d2b4b43e19a89a7f0988e404d1dc3212b0819"
          },
          {
            "left": "2da9b9faee33ebb6abfecef71576f706ef5a616508a49163b772d52131580879"
          },
          {
            "right": "639fee662f799852b5e35537d033c80e46bdcf5224d9593009b5e68cbe166f76"
          },
          {
            "right": "7931d7f2b94b0845b776ec6d92da7b76b7a6f23859d80a15f8650c46f8d6b415"
          }
        ]
      }
    ]
  }
}
