=== BMT-StealthGroup/credential-commons/dist/schemas/public/Credential/v2/CivicBasic.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "civ:Credential:CivicBasic",
  "type": "object",
  "properties": {
    "id": {
      "type": [
        "null",
        "string"
      ]
    },
    "issuer": {
      "type": "string"
    },
    "issued": {
      "type": "string"
    },
    "identifier": {
      "type": "string"
    },
    "expiry": {
      "type": [
        "null",
        "string"
      ]
    },
    "version": {
      "type": "string"
    },
    "type": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "claims": {
      "type": "object",
      "properties": {
        "type": {
          "type": "object",
          "properties": {
            "phone": {
              "type": "object",
              "properties": {
                "countryCode": {
                  "type": "string"
                },
                "number": {
                  "type": "string"
                }
              }
            },
            "email": {
              "type": "object",
              "properties": {
                "domain": {
                  "type": "string"
                },
                "user": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "signature": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "merkleRoot": {
          "type": "string"
        },
        "anchor": {
          "type": "object",
          "properties": {
            "subject": {
              "type": "object",
              "properties": {
                "pub": {
                  "type": "string"
                },
                "label": {
                  "type": "string"
                },
                "data": {
                  "type": "string"
                },
                "signature": {
                  "type": "string"
                }
              }
            },
            "walletId": {
              "type": "string"
            },
            "cosigners": {
              "type": "array",
              "items": {
                "type": "object"
              }
            },
            "authority": {
              "type": "object",
              "properties": {
                "pub": {
                  "type": "string"
                },
                "path": {
                  "type": "string"
                }
              }
            },
            "coin": {
              "type": "string"
            },
            "tx": {
              "type": "string"
            },
            "network": {
              "type": "string"
            },
            "value": {
              "type": "number"
            },
            "type": {
              "type": "string"
            },
            "civicAsPrimary": {
              "type": "boolean"
            },
            "schema": {
              "type": "string"
            }
          }
        },
        "leaves": {
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    }
  },
  "additionalProperties": false
}

=== BMT-StealthGroup/credential-commons/__integrations__/fixtures/correct/Credential/Address.json
{
  "id": null,
  "issuer": "jest:test",
  "issued": "2018-07-11T21:27:58.370Z",
  "identifier": "civ:Credential:CivicBasic",
  "expiry": null,
  "version": "1",
  "type": [
    "Credential",
    "civ:Credential:CivicBasic"
  ],
  "claims": {
    "type": {
      "phone": {
        "countryCode": "yyFrehmHEJ",
        "number": "3POrcHtB8z"
      },
      "email": {
        "domain": "U3NLHojOOp",
        "user": "c6HhJPRvuN"
      }
    }
  },
  "signature": {
    "type": "CivicMerkleProof2018",
    "merkleRoot": "1012b25234780f8a4f84a0755e9cb816ba9fda7aaa71f6508da7b906266bc78e",
    "anchor": {
      "subject": {
        "pub": "xpub661MyMwAqRbcFNXRK7kdsoidhiyfqiwhVhbphdKZjqnik83L1w1mWsPwVrsvbRrPa7sysiJRRBxr6jyrCbPScdXkhSjyYtQtFfwxGBwrBzn",
        "label": "civ:Credential:CivicBasic",
        "data": "1012b25234780f8a4f84a0755e9cb816ba9fda7aaa71f6508da7b906266bc78e",
        "signature": "304402204351b07b996b791fc3e61657cb2d98352cfa76880fec119a5d6e8741f4eea4780220742177be9e7c262f287604e46ad2d60de1e125ad84a477de7285fa35d6400f3f"
      },
      "walletId": "5b46766797839ec00319c0f620d83c55",
      "cosigners": [
        {
          "pub": "xpub661MyMwAqRbcFsJdqG7dL15Kxp1xJmjjGDYk8iAjLBYnwkxqcoHa9RWNFRqABesVjGh5rpLQYQ8CPRZRm63q4hemqqwu6UaLCmwMNKbnfmq"
        },
        {
          "pub": "xpub661MyMwAqRbcGzD4qjk6XDXvLf2JtA5BX1S3SiMYWPncxC7LYx1UL51Lapy8CW9FFZyV6qwdZ1GiNMY9X9b5QptV14vFCkjjcAmQ88gaRaU"
        }
      ],
      "authority": {
        "pub": "xpub661MyMwAqRbcGvSnxEsF3ozUA1kqjNE9fdBpDjKG6YvMuBCjiwf5w9DxDPubPpgpueWkczH21gJ1a7t7J7xw6fTiQmFiWd57opAgTRCCq1H",
        "path": "/0/0/1/147"
      },
      "coin": "tbch",
      "tx": "0200000001e84eaa0912aaadfb5b165030d380bb7f15c79e713f75a41c4860b53f187704cc00000000fdfe0000483045022100e86e3291e8a56250ece799b002b2b436e28eb8a099f5f949d16fc33a2936ecc0022005bb58206126b3235fd7f6c1bc9a5c241bf509dac9a152d510c13c7459bb9ba141483045022100c3f506fdff31dd5fa9eacf35733c8bc6ff6ebe5ea5f11ca5fc880dfed2ca9d13022000db27afc4ec629c70585b9ab1165ebec218d3b383330b5d29de2cc377fe300e414c695221030270e32d3e048bbcc3c5d188fb54dac1364d2fde6affbfe41236f24ddb6d42d32102d8667c7879573df1946f678f22d604352000c9524cfecd4bc4a57217e3f9b2582103be0b07cea135d72587187a44bfae32dc859e52f636e79efefefddde366b099e153aeffffffff028bfd45010000000017a91408521a0b26773d80f2da09ff8003a9d9a603e91287fb1700000000000017a914eb53aa8f835956f4e686cd02a980bda6c87a88b88700000000",
      "network": "testnet",
      "value": 21370994,
      "type": "permanent",
      "civicAsPrimary": false,
      "schema": "tbch-20180201"
    },
    "leaves": [
      {
        "identifier": "civ:Meta:issuer",
        "value": "urn:issuer:f17d16ece5bba0b757bb0093203db37a8d33c74809ee0bed95318d8774ddec6d:jest:test",
        "claimPath": "meta.issuer",
        "targetHash": "0c125422bb58c68d8781469682a25be558c0cb681d093036bb55fc5acbc925e0",
        "proof": [
          {
            "right": "43ba44b792b0eb1cd58348e83f905631229edbce16c35e293e0384e758285aa5"
          },
          {
            "right": "9e1b6a02d37e2e34fcd30b98f70104855093a84e92ca1ee04b60de391e1c3e1e"
          },
          {
            "right": "268d8eacc521b121e5565b0f4d4ec24ce80e269d66ab2808cf3d1d0961765b2c"
          },
          {
            "right": "016a5ca3329124861a21c5689609c9763c9a5dce8186f4443840f87610371fc6"
          }
        ]
      },
      {
        "identifier": "civ:Meta:issued",
        "value": "urn:issued:a70480ec2ca162878a4530f4523abd2ccb358c24d8f6e0ba6d3ed5613a7d9676:2018-07-11T21:27:58.370Z",
        "claimPath": "meta.issued",
        "targetHash": "43ba44b792b0eb1cd58348e83f905631229edbce16c35e293e0384e758285aa5",
        "proof": [
          {
            "left": "0c125422bb58c68d8781469682a25be558c0cb681d093036bb55fc5acbc925e0"
          },
          {
            "right": "9e1b6a02d37e2e34fcd30b98f70104855093a84e92ca1ee04b60de391e1c3e1e"
          },
          {
            "right": "268d8eacc521b121e5565b0f4d4ec24ce80e269d66ab2808cf3d1d0961765b2c"
          },
          {
            "right": "016a5ca3329124861a21c5689609c9763c9a5dce8186f4443840f87610371fc6"
          }
        ]
      },
      {
        "identifier": "civ:Meta:expiry",
        "value": "urn:expiry:610e3be90f229bfc43a3c7c7fb2051059826016d907282ca9e49ae553415e625:null",
        "claimPath": "meta.expiry",
        "targetHash": "75a59e98cc76dc6278c352699517520163b0b8ccf9bf69c03849b6c760e916e4",
        "proof": [
          {
            "right": "1c8119619c8684f78b4049a41dcce76dd51f0e3e2505ea7fbf2a50b991384de9"
          },
          {
            "left": "ab365029f8992c072b731ba949c6adee980dbc318f123308d8b0fc53380436a8"
          },
          {
            "right": "268d8eacc521b121e5565b0f4d4ec24ce80e269d66ab2808cf3d1d0961765b2c"
          },
          {
            "right": "016a5ca3329124861a21c5689609c9763c9a5dce8186f4443840f87610371fc6"
          }
        ]
      }
    ]
  }
}
